// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.DatabaseContext;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(CommunityGardenDatabase))]
    [Migration("20260205225210_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("WebApplication1.Models.GardenMember", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailContact")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullLegalName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("GardeningInterests")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("MembershipTier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PreferOrganicOnly")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("INTEGER");

                    b.HasKey("MemberId");

                    b.HasIndex("EmailContact")
                        .IsUnique();

                    b.ToTable("GardenMembers");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            EmailContact = "sarah.j@email.com",
                            FullLegalName = "Sarah Johnson",
                            GardeningInterests = "Tomatoes, Herbs, Peppers",
                            MembershipTier = "Premium",
                            PreferOrganicOnly = true,
                            RegistrationDate = new DateTime(2022, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 8
                        },
                        new
                        {
                            MemberId = 2,
                            EmailContact = "m.chen@email.com",
                            FullLegalName = "Michael Chen",
                            GardeningInterests = "Root vegetables, Squash",
                            MembershipTier = "Basic",
                            PreferOrganicOnly = false,
                            RegistrationDate = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 2
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.GardenPlot", b =>
                {
                    b.Property<int>("PlotIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedGardenerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastMaintenanceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlotDesignation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoilType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SquareMeters")
                        .HasColumnType("REAL");

                    b.Property<bool>("WaterAccessAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("YearlyRentalFee")
                        .HasColumnType("TEXT");

                    b.HasKey("PlotIdentifier");

                    b.HasIndex("AssignedGardenerId");

                    b.HasIndex("PlotDesignation")
                        .IsUnique();

                    b.ToTable("GardenPlots");

                    b.HasData(
                        new
                        {
                            PlotIdentifier = 1,
                            AssignedGardenerId = 1,
                            IsOccupied = true,
                            LastMaintenanceDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlotDesignation = "A001",
                            SoilType = "Clay-Loam",
                            SquareMeters = 25.5,
                            WaterAccessAvailable = true,
                            YearlyRentalFee = 150m
                        },
                        new
                        {
                            PlotIdentifier = 2,
                            IsOccupied = false,
                            LastMaintenanceDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlotDesignation = "A002",
                            SoilType = "Sandy-Loam",
                            SquareMeters = 30.0,
                            WaterAccessAvailable = true,
                            YearlyRentalFee = 175m
                        },
                        new
                        {
                            PlotIdentifier = 3,
                            AssignedGardenerId = 2,
                            IsOccupied = true,
                            LastMaintenanceDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlotDesignation = "B001",
                            SoilType = "Loamy",
                            SquareMeters = 20.0,
                            WaterAccessAvailable = true,
                            YearlyRentalFee = 125m
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.HarvestRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CollectionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CropName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("HarvestNotes")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOrganicCertified")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlotIdentifier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualityScore")
                        .HasColumnType("INTEGER");

                    b.Property<double>("QuantityKilograms")
                        .HasColumnType("REAL");

                    b.HasKey("RecordId");

                    b.HasIndex("MemberId");

                    b.HasIndex("PlotIdentifier");

                    b.ToTable("HarvestRecords");

                    b.HasData(
                        new
                        {
                            RecordId = 1,
                            CollectionDate = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CropName = "Cherry Tomatoes",
                            HarvestNotes = "Excellent yield, very sweet",
                            IsOrganicCertified = true,
                            MemberId = 1,
                            PlotIdentifier = 1,
                            QualityScore = 5,
                            QuantityKilograms = 12.5
                        },
                        new
                        {
                            RecordId = 2,
                            CollectionDate = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CropName = "Carrots",
                            HarvestNotes = "Good size, some slight pest damage",
                            IsOrganicCertified = false,
                            MemberId = 2,
                            PlotIdentifier = 3,
                            QualityScore = 4,
                            QuantityKilograms = 8.3000000000000007
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.GardenPlot", b =>
                {
                    b.HasOne("WebApplication1.Models.GardenMember", "CurrentTenant")
                        .WithMany("ManagedPlots")
                        .HasForeignKey("AssignedGardenerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentTenant");
                });

            modelBuilder.Entity("WebApplication1.Models.HarvestRecord", b =>
                {
                    b.HasOne("WebApplication1.Models.GardenMember", "Harvester")
                        .WithMany("RecordedHarvests")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.GardenPlot", "SourcePlot")
                        .WithMany("HarvestHistory")
                        .HasForeignKey("PlotIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Harvester");

                    b.Navigation("SourcePlot");
                });

            modelBuilder.Entity("WebApplication1.Models.GardenMember", b =>
                {
                    b.Navigation("ManagedPlots");

                    b.Navigation("RecordedHarvests");
                });

            modelBuilder.Entity("WebApplication1.Models.GardenPlot", b =>
                {
                    b.Navigation("HarvestHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
